### ISSUE TITLE
Pretrained model missing.

### ISSUE THREAD

**Issue by tanzeyy** [HaomingCai/PIPAL-dataset#1]
Hello, 
  I want to rank the qualities of some images, and I wonder is there any plan for releasing the pretrained model? Thanks!

**Comment by HaomingCai** [comment]
> Hello,
> I want to rank the qualities of some images, and I wonder is there any plan for releasing the pretrained model? Thanks!

Thanks for paying attention to PIPAL and codebase. 

We currently don't release the well-trained model (our SWD) due to the journal version of PIPAL being still under review. 
This codebase mainly helps you to train your model on the PIPAL dataset. The core python script is the dataset operation.
