### ISSUE TITLE
test the test_iqa.yml

### ISSUE THREAD

**Issue by ke-s** [HaomingCai/PIPAL-dataset#2]
Hello, when I was testing your code, I found that you did not give the label data of VAL and test set, so I can’t run the testIQA.yml, how can this solve this?
The error is “FileNotFoundError: [Errno 2] No such file or directory: '/home/hmcai/home/Dataset/PIPAL/PIPAL_Partition/FullDataset/Full_EloMOSV2'”

**Comment by HaomingCai** [comment]
> Hello, when I was testing your code, I found that you did not give the label data of VAL and test set, so I can’t run the testIQA.yml, how can this solve this?
> The error is “FileNotFoundError: [Errno 2] No such file or directory: '/home/hmcai/home/Dataset/PIPAL/PIPAL_Partition/FullDataset/Full_EloMOSV2'”

Thanks for paying attention to PIPAL and related codebases.
The label data of VAL and VAL itself are in the Codalab Server (NTIRE2021/NTIRE2022). We currently don't release the label (test and validation) and well-trained model (SWD).
