### ISSUE TITLE
 distortion type

### ISSUE THREAD

**Issue by skk-k** [HaomingCai/PIPAL-dataset#3]
Hello, can you provide the distortion type names corresponding to all the images?
If 
A0001_01_01.bmp represents, what is the distortion type
What a distortion type does the A0001_01_02.bmp represent
thank you very much

**Comment by HaomingCai** [comment]
> Hello, can you provide the distortion type names corresponding to all the images?
> If
> A0001_01_01.bmp represents, what is the distortion type
> What a distortion type does the A0001_01_02.bmp represent
> thank you very much

Thanks for leaving your question here.
Could you please send me a request email? We will not release the data structure and the name rule this month. 

My email address is : haomingcai@link.cuhk.edu.cn
