### ISSUE TITLE
Ask about MOS validation.txt

### ISSUE THREAD

**Issue by sonata13** [HaomingCai/PIPAL-dataset#7]
Hi, could you provide the MOS data ?

Thank you, I am looking forward for your reply

**Comment by sonata13** [comment]
Sorry, just found it.
Thanks

**Comment by HaomingCai** [comment]
> Hi, could you provide the MOS data ?
> 
> Thank you, I am looking forward for your reply

We provide the MOS score of PIPAL-Train (200 ref x 116 distortions) for NTIRE2021/2022. You can find it in Codalab. Please let me know if you have any other questions, and I will reply ASAP.

**Comment by sonata13** [comment]
Hi HaomingCai,

Thank you for your fast reply.
Could we have access for validation MOS list?
I could not find it in the repository.

**Comment by HaomingCai** [comment]
> Hi HaomingCai, Thank you for your fast reply. Could we have access for validation MOS list? I could not find it in the repository.
> […](#)

The current answer is NO. We currently don't have plan to release the MOS score of PIPAL-valid / PIPAL-test used in NTIRE. However, the Codalab sever is constantly accesible. With specific txt format (see Codalab), you can upload the output of your model to test the performance (SRCC/PLCC) on PIPAL valid and test set at Codalab.

**Comment by sonata13** [comment]
Thank you for your reply!
Have a nice day
